version: '3.8'
services:
  service-1:
    build: ./service-1
    image: mattcolemann/animal_generator_service-1:latest
    container_name: animal_generator_service-1
    ports: 
    - target: 5000
      published: 80
    environment:
      DATABASE_URI: ${DATABASE_URI}

  service-2:
    build: ./service-2
    image: mattcolemann/animal_generator_service-2:latest
    container_name: animal_generator_service-2

  service-3:
    build: ./service-3
    image: mattcolemann/animal_generator_service-3:latest
    container_name: animal_generator_service-3

  service-4:
    build: ./service-4
    image: mattcolemann/animal_generator_service-4:latest
    container_name: animal_generator_service-4
