version: '3.8'
services:
  service-1:
    build: ./service-1
    image: ${DOCKER_USERNAME}/animal_generator_service-1:latest
    container_name: animal_generator_service-1
    ports: 
    - target: 5000
      published: 80
    environment:
      DATABASE_URI: ${DATABASE_URI}
    deploy:
      replicas: 4

  service-2:
    build: ./service-2
    image: ${DOCKER_USERNAME}/animal_generator_service-2:latest
    container_name: animal_generator_service-2
    deploy:
      replicas: 4

  service-3:
    build: ./service-3
    image: ${DOCKER_USERNAME}/animal_generator_service-3:latest
    container_name: animal_generator_service-3
    deploy:
      replicas: 4

  service-4:
    build: ./service-4
    image: ${DOCKER_USERNAME}/animal_generator_service-4:latest
    container_name: animal_generator_service-4
    deploy:
      replicas: 4
