all:
  children:
    managers:
      hosts:
        10.154.0.29:
    workers:
      hosts:
        10.154.0.25:
    load-balancer:
      hosts:
        nginx:
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'